### PR TITLE
Added the ability to add settings at runtime.

### PR DESCRIPTION
**Pull request by josuave**
Altered Settings to have the ability to have additions during runtime.
Added a very dirty example, DesktopLocationToolbar Top and Left tracking...

### CODE REVIEW

**Comment by dremin** [comment]
Looks good, but could you please remove all of the Any CPU build configurations that VS added?

**Comment by josuave** [comment]
Yes. I’ll put in a pull request when complete

Sent from my iPhone

On Mar 19, 2019, at 6:53 PM, Sam Johnson <notifications@github.com<mailto:notifications@github.com>> wrote:


Looks good, but could you please remove all of the Any CPU build configurations that VS added?

**Comment by josuave** [comment]
Not sure whats up with x86

**Comment by dremin** [comment]
Looks like a lot of extra files got modified that shouldn't have been, compared to master, as far as I can tell.

**Comment by josuave** [comment]
When digging through I found that many of the projects had entries for AnyCPU. Some of the debug/release configurations had output to the bin directory in the project folder rather then the one in the solution folder. So I went through and verified each project for debug/release and x86/x64.

From what I can see all the projects output to the proper spots now

**Comment by dremin** [comment]
Maybe I need to look at the AppVeyor config to see what's up. My PC is currently out of commission so I haven't had a chance to look too hard at it yet

**Comment by josuave** [comment]
I just close the Paul request. I’m going to get current with the official repo, reintroduce my changes for settings and put in a new pull request (with out the sample extension for now)

**Pull request closed without merging**
