### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by austinHeisleyCook**
added main calculator since windows basic calculator is broken to activation by cairodeskop

### CODE REVIEW

**Comment by austinHeisleyCook** [comment]
poissles

**Comment by austinHeisleyCook** [comment]
xa

**Comment by austinHeisleyCook** [comment]
i am trying to add basic calculator for Cairo so it uses this calculator instead of the shell not recognizing with the class not recognized error. most features work i am fixing to squared function button but all function s are tested to perform as expected i am working on a browser for cairotoo

**Comment by austinHeisleyCook** [comment]
@dremin  is this ok

**Comment by josuave** [comment]
I believe that this issue is best handled outside of cairo. We do not want to start creating hacks or workarounds that handle situations that are not in scope for cairo or shel replacements, in general. This is best handled by utilizing another calculator application.

**Comment by austinHeisleyCook** [comment]
> 
> 
> I believe that this issue is best handled outside of cairo. We do not want to start creating hacks or workarounds that handle situations that are not in scope for cairo or shel replacements, in general. This is best handled by utilizing another calculator application.

understood

**Pull request closed without merging**
