### PR TITLE
Add .NET 6 target and ARM64 build

### PR DESCRIPTION
**Pull request by dremin**

### CODE REVIEW

**Comment by dremin** [comment]
Oh dear, the .NET 6 version is what gets added to the installer, along with the entire framework. Will need to set up publish profiles for the various targets and adjust the installer to only generate for the ones we want.

**Comment by dremin** [comment]
@josuave If we include the framework with Cairo, the installer exe is about 60 MB. I think this is worth it because then users will not need to install .NET 6, it will be safer to offer via auto updates, and we have more freedom to update the framework going forward. Do you agree?

**Comment by josuave** [comment]
We can start that way. If there is interest in a framework dependent version then we can supply that later

**Comment by dremin** [comment]
The ARM64 build works, but is currently without WinSparkle updater support, as there is no ARM release of WinSparkle.

**Review by josuave — APPROVED** [review]

**Pull request merged**
