### PR TITLE
Handle Explorer restart

### PR DESCRIPTION
**Pull request by dremin**
When the TaskbarCreated message is received, we can assume another shell has been launched. This PR adds a WindowManager event that is invoked when this message is received. We handle this message for two purposes:
- Recreate our AppBar windows so that if Explorer restarted, the workarea is restored (#861)
- Recreate our Desktop windows so that if Explorer restarted, the no-longer-existing desktop window is recreated. Restarting Explorer closes our desktop window because we set the Explorer desktop window as its parent.

TaskbarCreatedMonitor is basically the same as [ExplorerMonitorWindow from RetroBar](https://github.com/dremin/RetroBar/blob/master/RetroBar/Utilities/ExplorerMonitor.cs).

### CODE REVIEW

**Comment by dremin** [comment]
Found a bug with the LowLevelKeyboardListener in the DesktopNavigationToolbar with this change. Marked as draft until I fix that.

**Comment by dremin** [comment]
All fixed :)

**Review by josuave — APPROVED** [review]

**Comment by JongHong** [comment]
Or is it purely on this issue?

**Pull request merged**
