### PR TITLE
Publish to Windows Package Manager (WinGet)

### PR DESCRIPTION
**Pull request by vedantmgoyal2009**
This action automatically generates manifests for WinGet Community Repository ([microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)) and submits them.

Before merging this:
1. Please add a GitHub token with `public_repo` scope as a repository secret and rename the secret name in the workflow.
2. Fork [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs) under @cairoshell
3. Mark new releases as a release, and not a pre-release (since the action won't trigger when a pre-release is published.

* Resolves https://github.com/cairoshell/cairoshell/issues/677

### CODE REVIEW

**Comment by vedantmgoyal2009** [comment]
@dremin please merge the pull request if everything seems fine... it won't take much of your time...

**Comment by dremin** [comment]
@vedantmgoyal2009 Apologies for the delay, I will get this merged!

**Comment by vedantmgoyal2009** [comment]
Thanks 🙏🏻

**Comment by vedantmgoyal2009** [comment]
@dremin any updates?

**Review by dremin — APPROVED** [review]

**Pull request merged**
