### PR TITLE
Fixing Issues

### PR DESCRIPTION
**Pull request by josuave**
A misc. refactoring and a fix for bug #195

### CODE REVIEW

**Comment by josuave** [comment]
Added code to fix issue #193

**Comment by dremin** [comment]
Assuming you closed due to the 195 conflict, do you plan on re-opening with that removed?

**Comment by josuave** [comment]
Ya. I need to boot my laptop up tonight

Sent from my iPhone

On Sep 5, 2018, at 7:06 PM, Sam Johnson <notifications@github.com<mailto:notifications@github.com>> wrote:


Assuming you closed due to the 195 conflict, do you plan on re-opening with that removed?

**Comment by josuave** [comment]
Reopened

Sent from my iPhone

On Sep 5, 2018, at 7:06 PM, Sam Johnson <notifications@github.com<mailto:notifications@github.com>> wrote:


Assuming you closed due to the 195 conflict, do you plan on re-opening with that removed?

**Pull request closed without merging**
