### PR TITLE
Implement command framework

### LINKED ISSUE #144: [Feature Request] Impliment Command Framework
This would allow us to Customize much of Cairo, similar to how office allows you to setup custom Quick Launch and Ribbon objects.

### PR DESCRIPTION
**Pull request by dremin**
Introduces an ICairoCommand interface. Cairo and extensions can register commands in the same way shell extensions are registered. Commands consist of an action and metadata that describes the command--its identifier, label, description, parameters, and availability. Commands can can dynamically change their availability, label, etc based on changes to settings or other state.

Introduces a CommandService, similar to ExtensionService, that manages the list of and lifecycle of commands. It initializes all commands and disposes of them.

The CommandService is also what is responsible for invoking commands. Commands are invoked using their unique identifier, and can accept a key/value pair list of parameters.

I've created several commands so far, mostly representing the items in the Cairo menu and a few others. Before I mark this PR as ready, I plan to continue refactoring to replace existing code with commands then removing the old implementations.

As an example usage of commands, I've converted the Cairo menu to be dynamically generated by a list of commands. The Places menu has also been re-implemented around commands. The goal here is to make the menus fully customizable in the future.

There are interfaces, such as ICairoShellFolderCommandInfo and ICairoShellItemCommandInfo, which allow commands to declare their availability and label within shell context menus. Those commands are dynamically shown in menus.

Ultimately once the commands are all implemented, we will be in a place to deconstruct the rest of the `Cairo Desktop` project (i.e. desktop, taskbar, stacks, etc) now that the code is de-tangled.

Fixes #144

### CODE REVIEW

**Comment by dremin** [comment]
In the latest push, I've added interfaces which commands can implement to indicate their support for displaying in shell context menus. All of the old implementations have been removed and replaced with this new dynamic system.

**Comment by dremin** [comment]
@josuave One thing I am on the fence regarding is the `Start()` method in commands. I originally added this to provide an "out" in case there is a circular dependency when using injection, so a command could get a service from within the Start method instead of via injection. However, I haven't run into this within practical usage, and am beginning to think it is unnecessary. Do you agree?

**Comment by josuave** [comment]
@dremin i know what your saying. I would not implement anything yet unless needed to do the job right now. Keep it simple and to the point. Handling what if scenarios will usually back you into a corner and get your hands tied.

**Comment by dremin** [comment]
@josuave Thanks! I went ahead and removed it.

I think this is ready now.

**Comment by dremin** [comment]
@josuave Not sure if you saw but this is ready for review :)

**Review by josuave — APPROVED** [review]

**Pull request merged**
