### PR TITLE
Multiple Resolution:  Issue #193 & Feature #200

### PR DESCRIPTION
**Pull request by josuave**
I have added back the code to prevent win key repeats
I have implemented Alt+F4 on the Cairo Desktop

### CODE REVIEW

**Comment by dremin** [comment]
Looks good, thanks! I may move some of those functions out of the Cairo class because that was intended to be only for styles and less code, but that is all good for now.

**Comment by josuave** [comment]
Cool. I’ll review to see if I can find a better spot also. The way the functions read made sense.

Sent from my iPhone

On Sep 25, 2018, at 1:13 AM, Sam Johnson <notifications@github.com<mailto:notifications@github.com>> wrote:


Merged #199<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcairoshell%2Fcairoshell%2Fpull%2F199&data=02%7C01%7C%7C1fb7576cc2c04710d82608d622a598c1%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636734491950866244&sdata=LXLGZ0d3bbzNp%2Fb0oIujB%2BoTQv0O38OSlHEx3QEqrGE%3D&reserved=0> into master.

**Comment by dremin** [comment]
Actually I'm also not seeing the alt-f4 working either, maybe something missing?

**Comment by josuave** [comment]
Let’s build up the cases and we can evaluate completely

Sent from my iPhone

On Oct 19, 2018, at 11:32 PM, Sam Johnson <notifications@github.com<mailto:notifications@github.com>> wrote:


Actually I'm also not seeing the alt-f4 working either, maybe something missing?

**Pull request merged**
