### PR TITLE
DynamicDesktop History Access

### PR DESCRIPTION
**Pull request by josuave**
Added DynamicDesktop History access along with ability to clear history
Other Refactorings

### CODE REVIEW

**Comment by dremin** [comment]
Few things:
1. Going to root of drive adds an item with no label
2. Entries added on navigation even if you didn't go anywhere (example: click home button a few times)
3. Style not correct (maybe we could refactor styles to apply to all contextmenus without explicit definition?)

If you're able to tackle this-- awesome, please update the PR. Otherwise, let me know and I will merge and look at these issues.

**Comment by josuave** [comment]
All issues resolved. not sure if I have "updated" the pull request yet. looking at the commits in this PR I do see the latest

**Comment by josuave** [comment]
I’ll look into it

Sent from my iPhone

On Jul 25, 2018, at 10:26 PM, Sam Johnson <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks! Sorry I'm traveling so I can't take a look for a few days, it looks good from just taking a peek but could you please remove the anycpu configurations added by the last commit?

**Comment by josuave** [comment]
Made changes

**Comment by dremin** [comment]
Looks good! I'm merging, but wanted to double check one thing: I saw a new WindowsTaskbarHelper class added to both the main project and the WindowsTasks project that looks duplicated. Is it OK to keep only the copy in the WindowsTasks project?

**Comment by josuave** [comment]
I just saw this, if there are no references drop it. Most likely either a drag drop or I was trying something out. Either way not needed

Sent from my iPhone

On Aug 1, 2018, at 6:07 PM, Sam Johnson <notifications@github.com<mailto:notifications@github.com>> wrote:


Looks good! I'm merging, but wanted to double check one thing: I saw a new WindowsTaskbarHelper class added to both the main project and the WindowsTasks project that looks duplicated. Is it OK to keep only the copy in the WindowsTasks project?

**Comment by josuave** [comment]
I dug in and found that these two files are in the directory structure but not included in the projects. I was testing some functionality of pulling the Windows Taskbar Button Progress values. This would help us indicate download progress as well as other application progress values. It was a flop and these 2 files can be removed.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Pull request merged**
